services:
  postgis:
    image: 'kartoza/postgis:14'
    healthcheck:
      test: pg_isready -h localhost -U proyecto -d proyectodb
      interval: 10s
      timeout: 5s
      retries: 5
    labels:
      org.springframework.boot.service-connection: postgres
    ports:
      - "25432:5432"
    environment:
      - 'POSTGRES_USER=proyecto'
      - 'POSTGRES_PASSWORD=proyectovm'
      - 'POSTGRES_DB=proyectodb'
      - 'DEFAULT_ENCODING=UTF8'
    volumes:
      - 'dbdata:/var/lib/postgresql'
  pygeoapi:
    image: 'geopython/pygeoapi:latest'
    ports:
      - "5000:80"
    environment:
      - 'PYGEOAPI_CONFIG=/pygeoapi/local.config.yml'
    volumes:
      - './pygeoapi-config-act.yml:/pygeoapi/local.config.yml'
    depends_on:
      postgis:
        condition: service_healthy
  rabbitmq:
    image: rabbitmq:4-management
    container_name: adabyron-rabbitmq
    ports:
      - "5672:5672"   # Puerto de comunicación de la aplicación (AMQP)
      - "15672:15672" # Interfaz web de administración
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: always
  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: unless-stopped
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
volumes:
  dbdata:
  rabbitmq_data: